CREATE TABLE IF NOT EXISTS vault_import_session (
    id CHAR(36) NOT NULL PRIMARY KEY,
    owner_id CHAR(36) NOT NULL,
    status VARCHAR(20) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_format VARCHAR(16) NOT NULL,
    byte_size BIGINT NOT NULL,
    row_count INT NOT NULL DEFAULT 0,
    ready_count INT NOT NULL DEFAULT 0,
    needs_review_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    model_provider VARCHAR(64) NULL,
    model_name VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    candidates_ciphertext LONGBLOB NULL,
    candidates_nonce BINARY(12) NULL,
    candidates_algo_version INT NULL,
    candidates_key_id SMALLINT NULL,
    expires_at DATETIME(6) NOT NULL,
    committed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    INDEX idx_vault_import_owner_created (owner_id, created_at),
    INDEX idx_vault_import_expires (expires_at),
    INDEX idx_vault_import_owner_status (owner_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
